# Refference here: https://docs.travis-ci.com/user/job-lifecycle/

language: node_js
node_js:
  - "10.13.0"
cache: npm

install:
  - npm install

script:
  - npm test
after_success: true

after_failure: false

deploy:
  - provider: CodeDeployServiceRole
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  application: fpa_backend
  deployment_group: fpa_backend
  region: ap-northeast-2

after_script: true
