language: node_js
node_js:
- 10.13.0
cache: npm
install:
- npm install
script:
- npm test
notifications:
  slack:
    rooms:
    - everyawake:AI8aX9YtvJ0G92adeuClf8vr#st-backend-alert
    on_pull_requests: false
    on_success: change
    on_failure: always
before_deploy:
- zip -x node_modules/\* -r fpa-backend *
- mkdir -p deploy
- mv fpa-backend.zip deploy/fpa-backend.zip
deploy:
  provider: heroku
  api_key: "$HEROKU_API_KEY"
  app: fpa-backend
  run:
    - "npm install"
  # matrix:
  # - provider: s3
  #   access_key_id: "$AWS_ACCESS_KEY"
  #   secret_access_key: "$AWS_SECRET_KEY"
  #   bucket: fpa-production-deploy
  #   region: us-east-2
  #   skip_cleanup: true
  #   acl: public_read
  #   local_dir: deploy
  #   wait-until-deployed: true
  #   on:
  #     repo: everyawake/PRJ-FPA-Backend
  #     branch: master
  # - provider: codedeploy
  #   access_key_id: "$AWS_ACCESS_KEY"
  #   secret_access_key: "$AWS_SECRET_KEY"
  #   bucket: fpa-production-deploy
  #   key: fpa-backend.zip
  #   bundle_type: zip
  #   application: fpa-backend-deploy-app
  #   deployment_group: fpa-backend-codedeploy
  #   region: us-east-2
  #   wait-until-deployed: true
  #   on:
  #     repo: everyawake/PRJ-FPA-Backend
  #     branch: master


