# Refference here: https://docs.travis-ci.com/user/job-lifecycle/

language: node_js
node_js:
  - "10.13.0"
cache: npm

install:
  - npm install

script:
  - npm test
  - if ["$TRAVIS_BRANCH" = "master"]; then npm run pre-deploy && npm run deploy fi
  # - provider: codedeploy
  #   access_key_id: $AWS_ACCESS_KEY
  #   secret_access_key: $AWS_SECRET_KEY
  #   bucket: fpa-production-deploy
  #   key: fpa-backend.zip
  #   bundle_type: zip
  #   application: fpa-deploy
  #   deployment_group: fpa-backend-deploy
  #   region: us-east-2
  #   wait-until-deployed: true
  #   on:
  #     repo: everyawake/PRJ-FPA-Backend
  #     branch: master
