version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/app/build
hooks:
  BeforeInstall:
    - location: cd /home/ubuntu/app/build
    - location: npm i
      runas: root
  ApplicationStart:
    - location: cd /home/ubuntu/app/build
    - location: npm run production
    runas: root
